<#
    ArcGPT shared tunnel helper.

    There is exactly ONE authoritative Cloudflare Quick Tunnel per running
    ArcGPT session. Both start-arcgpt.bat and Deploy-ArcGPT-Pages.bat resolve
    that tunnel through this script, so the launcher and the deployment can
    never end up pointing at two different trycloudflare.com hostnames.

    Why this file exists
    --------------------
    The ArcGPT Quick Tunnel URL is ephemeral: it changes every time
    cloudflared restarts and dies with it. It has to be discovered, never
    hard-coded. Previously start-arcgpt.bat discovered it by scanning
    %TEMP%\arcgpt-tunnel-*.log and Deploy-ArcGPT-Pages.bat ignored that
    entirely and opened a second tunnel of its own. The published bundle
    therefore pointed at the deploy tunnel while the launcher kept a
    different one alive, and the hosted site broke as soon as the deploy
    tunnel's window was closed.

    Resolution order (first healthy answer wins)
    --------------------------------------------
      1. The runtime state file written by whoever opened the tunnel.
      2. The newest %TEMP%\arcgpt-tunnel-*.log, which is where cloudflared
         writes the URL it published.
      3. Nothing. The caller is then allowed to open a new tunnel.

    Nothing here is persisted into git-tracked source. The state file lives in
    %TEMP% and holds a hostname and pids only: no credential, no session
    secret, no database string.

    Usage
    -----
      powershell -NoProfile -ExecutionPolicy Bypass -File ArcGPT-Tunnel.ps1 -Action Resolve
      powershell -NoProfile -ExecutionPolicy Bypass -File ArcGPT-Tunnel.ps1 -Action Validate -Url <url>
      powershell -NoProfile -ExecutionPolicy Bypass -File ArcGPT-Tunnel.ps1 -Action Record -Url <url> -Owned 1
      powershell -NoProfile -ExecutionPolicy Bypass -File ArcGPT-Tunnel.ps1 -Action KnownUrls
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('Resolve', 'Validate', 'Record', 'KnownUrls', 'ClearState')]
    [string]$Action,

    [string]$Url = '',
    [string]$ExpectedDb = 'arcgpt_new',
    [string]$TunnelPid = '',
    [string]$BackendPid = '',
    [string]$Owned = '0',
    [string]$Log = '',
    [string]$Report = ''
)

# NOTE on naming: $Log above is a [string] parameter, and PowerShell variable
# names are case-insensitive. Any `foreach ($log in ...)` written at SCRIPT
# scope therefore assigns into that typed variable, which coerces each
# FileInfo down to its path string and silently empties .Name and .FullName.
# Inside a function the loop variable is local, which is why the same loop can
# work in one place and fail in another. The loops below all use $entry for
# this reason. Keep it that way.

# ----------------------------------------------------------------------------
# Runtime state
# ----------------------------------------------------------------------------
# A fixed filename, not a random one: both launchers have to agree on where to
# look. It is a flat key=value file so it can be read back with Get-Content and
# understood at a glance when something goes wrong.
$StateFile = Join-Path $env:TEMP 'arcgpt-tunnel-state.txt'

function Write-Result {
    param([string[]]$Lines)
    $Lines | ForEach-Object { Write-Output $_ }
    exit 0
}

# Windows PowerShell 5.1's `Set-Content -Encoding UTF8` writes a BOM. The first
# line of a report then arrives with a stray invisible character in front of it,
# and a BOM-prefixed state file is one `set /p` away from being misread as part
# of a value. Everything written here is ASCII anyway, so write it without one.
function Write-Lines {
    param([string]$Path, [string[]]$Lines)
    if (-not $Path) { return }
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($Path, $Lines, $utf8NoBom)
}

function Read-State {
    $state = @{}
    if (-not (Test-Path -LiteralPath $StateFile)) { return $state }
    foreach ($line in @(Get-Content -LiteralPath $StateFile -ErrorAction SilentlyContinue)) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
        $eq = $trimmed.IndexOf('=')
        if ($eq -lt 1) { continue }
        $key = $trimmed.Substring(0, $eq).Trim()
        $val = $trimmed.Substring($eq + 1).Trim()
        $state[$key] = $val
    }
    return $state
}

function Save-State {
    param(
        [string]$TunnelUrl,
        [string]$TunnelPidValue,
        [string]$BackendPidValue,
        [string]$OwnedValue,
        [string]$LogPath
    )
    $lines = @(
        '# ArcGPT runtime tunnel state. Generated by ArcGPT-Tunnel.ps1.',
        '# Temporary by design: it lives in %TEMP%, is never committed, and',
        '# holds a hostname and pids only. Deleting it is harmless.',
        ('URL=' + $TunnelUrl),
        ('TUNNEL_PID=' + $TunnelPidValue),
        ('BACKEND_PID=' + $BackendPidValue),
        ('OWNED=' + $OwnedValue),
        ('LOG=' + $LogPath),
        ('CREATED=' + (Get-Date).ToString('yyyy-MM-ddTHH:mm:ss'))
    )
    # utf8 without a BOM: cmd's set /p would otherwise read a stray ï»¿ before URL=
    Write-Lines -Path $StateFile -Lines $lines
}

# ----------------------------------------------------------------------------
# Health validation
# ----------------------------------------------------------------------------
# server=ok, database=arcgpt_new and ollama=ok are all required. A tunnel that
# forwards traffic but points at the wrong database, or at a backend whose
# model provider never came up, is not a tunnel worth publishing a site
# against.
function Test-TunnelHealth {
    param(
        [string]$BaseUrl,
        [string]$ExpectedDatabase
    )

    $out = [ordered]@{
        ok = $false
        server = ''
        database = ''
        ollama = ''
        detail = ''
    }

    if ([string]::IsNullOrWhiteSpace($BaseUrl)) {
        $out.detail = 'no url'
        return $out
    }

    $target = $BaseUrl.TrimEnd('/') + '/api/health'
    try {
        $h = Invoke-RestMethod -Uri $target -TimeoutSec 15
    } catch {
        $out.detail = $_.Exception.Message
        return $out
    }

    if ($null -eq $h) {
        $out.detail = 'empty response'
        return $out
    }

    $out.server = [string]$h.server
    $out.database = [string]$h.database
    $out.ollama = [string]$h.ollama

    if ($out.server -ne 'ok') { $out.detail = 'server=' + $out.server; return $out }
    if ($out.ollama -ne 'ok') { $out.detail = 'ollama=' + $out.ollama; return $out }
    if ($out.database -ne $ExpectedDatabase) { $out.detail = 'database=' + $out.database; return $out }

    $out.ok = $true
    $out.detail = 'healthy'
    return $out
}

# ----------------------------------------------------------------------------
# Candidate discovery
# ----------------------------------------------------------------------------
function Get-LogTunnelUrl {
    param([string]$LogPath)

    # Test-Path and Get-Content both refuse an empty -LiteralPath, so a blank
    # path has to be turned away here rather than reaching them.
    if ([string]::IsNullOrWhiteSpace($LogPath)) { return '' }
    if (-not (Test-Path -LiteralPath $LogPath)) { return '' }

    $text = Get-Content -Raw -LiteralPath $LogPath -ErrorAction SilentlyContinue
    if (-not $text) { return '' }
    $m = [regex]::Match($text, 'https://[a-zA-Z0-9-]+\.trycloudflare\.com')
    if (-not $m.Success) { return '' }
    return $m.Value
}

# Every tunnel URL this machine has ever seen. The deploy script uses this to
# prove that a previously published, now-dead hostname is absent from the new
# bundle rather than assuming the build cleaned up after itself.
function Get-KnownTunnelUrls {
    $urls = New-Object System.Collections.Generic.List[string]

    $state = Read-State
    if ($state.ContainsKey('URL') -and $state['URL']) {
        if (-not $urls.Contains($state['URL'])) { $urls.Add($state['URL']) }
    }

    $logs = @(Get-ChildItem -LiteralPath $env:TEMP -Filter 'arcgpt-tunnel-*.log' -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending)
    foreach ($entry in $logs) {
        $u = Get-LogTunnelUrl -LogPath $entry.FullName
        if ($u -and -not $urls.Contains($u)) { $urls.Add($u) }
    }

    return $urls
}

# ----------------------------------------------------------------------------
# Actions
# ----------------------------------------------------------------------------
switch ($Action) {

    'Resolve' {
        $state = Read-State
        $candidates = New-Object System.Collections.Generic.List[string]

        if ($state.ContainsKey('URL') -and $state['URL']) {
            $candidates.Add($state['URL'])
        }
        if ($state.ContainsKey('LOG') -and $state['LOG']) {
            $fromLog = Get-LogTunnelUrl -LogPath $state['LOG']
            if ($fromLog -and -not $candidates.Contains($fromLog)) { $candidates.Add($fromLog) }
        }

        $logs = @(Get-ChildItem -LiteralPath $env:TEMP -Filter 'arcgpt-tunnel-*.log' -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending)
        foreach ($entry in $logs) {
            $u = Get-LogTunnelUrl -LogPath $entry.FullName
            if ($u -and -not $candidates.Contains($u)) { $candidates.Add($u) }
        }

        # Not named $report: PowerShell variable names are case-insensitive, so
        # that would overwrite the -Report parameter with an empty array and
        # the report would silently never be written.
        $lines = @()

        foreach ($candidate in $candidates) {
            $h = Test-TunnelHealth -BaseUrl $candidate -ExpectedDatabase $ExpectedDb
            if ($h.ok) {
                $lines += ('Reusing  : ' + $candidate)
                $lines += ('Health   : server=' + $h.server + ' database=' + $h.database + ' ollama=' + $h.ollama)
                $lines += 'Found by : %TEMP%\arcgpt-tunnel-state.txt and arcgpt-tunnel-*.log'

                # Exactly one bare URL on stdout, so cmd can read it with a plain
                # `set /p`. Nothing that needs a `for /f`: these launchers have a
                # documented history of losing their labels to for/f inside a
                # parenthesised block. An empty line means "no healthy tunnel".
                if ($Report) { Write-Lines -Path $Report -Lines $lines }
                Write-Output $candidate
                exit 0
            }
            $lines += ('Rejected : ' + $candidate + '  (' + $h.detail + ')')
        }

        $lines += 'Result   : no healthy ArcGPT tunnel. A new one has to be opened.'

        if ($Report) { Write-Lines -Path $Report -Lines $lines }
        Write-Output ''
        exit 0
    }

    'Validate' {
        $h = Test-TunnelHealth -BaseUrl $Url -ExpectedDatabase $ExpectedDb
        if ($h.ok) {
            Write-Result @(
                ('ARCGPT_TUNNEL_HEALTH=server=' + $h.server + ' database=' + $h.database + ' ollama=' + $h.ollama),
                'ARCGPT_TUNNEL_VALID=1'
            )
        } else {
            Write-Result @(
                ('ARCGPT_TUNNEL_HEALTH=' + $h.detail),
                'ARCGPT_TUNNEL_VALID=0'
            )
        }
    }

    'Record' {
        if ([string]::IsNullOrWhiteSpace($Url)) {
            Write-Result @('ARCGPT_TUNNEL_RECORDED=0', 'ARCGPT_TUNNEL_DETAIL=no url to record')
        }
        Save-State -TunnelUrl $Url.TrimEnd('/') `
            -TunnelPidValue $TunnelPid `
            -BackendPidValue $BackendPid `
            -OwnedValue $Owned `
            -LogPath $Log
        Write-Result @('ARCGPT_TUNNEL_RECORDED=1', ('ARCGPT_TUNNEL_DETAIL=' + $Url))
    }

    'KnownUrls' {
        foreach ($u in (Get-KnownTunnelUrls)) {
            Write-Output ('ARCGPT_KNOWN_URL=' + $u)
        }
        exit 0
    }

    'ClearState' {
        if (Test-Path -LiteralPath $StateFile) {
            Remove-Item -LiteralPath $StateFile -Force -ErrorAction SilentlyContinue
        }
        Write-Result @('ARCGPT_TUNNEL_CLEARED=1')
    }
}