-- =============================================================================
-- ArcGPT — Student Dataset Expansion (idempotent, transactional)
-- =============================================================================
-- Brings the institution to exactly STUDENTS_PER_DEPARTMENT ACTIVE students in
-- every existing department, and generates guardian, CGPA, backlog, residency
-- and randomized attendance data.
--
-- IMPORTANT — the numbers reconcile themselves. There is no hardcoded total.
-- With the current 6 departments and 50 students each the dataset ends at 300
-- students. If a tenth department is ever added it becomes 500, with no edit
-- here. Creating extra departments to reach a round total is deliberately NOT
-- done: the department list is the institution's, not the seed's.
--
-- Sources of truth (deliberate, to avoid conflicting copies):
--   * CGPA lives in `student_academic_summary`. It is NOT copied onto
--     `students`, and the profile view reads it from there.
--   * Active backlogs live in `backlogs`. The count is DERIVED by the view;
--     `student_academic_summary.backlog_count` is kept in sync as a cache only.
--   * Attendance percentage is never stored. It is computed by
--     `student_attendance_percentage` from the attendance records.
--   * Residency lives in `student_residency`. `hostel_allocations` is left
--     untouched so there is exactly one authority for DAY_SCHOLAR/HOSTELLER.
--
-- Reproducibility: setseed() pins the generator, so a re-run on a fresh database
-- produces the same dataset. Attendance is randomized at the individual
-- record level, never per department, so no department bias is introduced.
--
-- All data is synthetic. Names are common Indian given/family names; no real
-- individual's data is generated, and no existing row is deleted except the
-- attendance mark sheets, which are regenerated by design.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. Configuration — edit these three values and nothing else
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS seed_config;
CREATE TEMP TABLE seed_config (key TEXT PRIMARY KEY, value TEXT NOT NULL) ON COMMIT DROP;
INSERT INTO seed_config (key, value) VALUES
    ('students_per_department',  '50'),   -- target ACTIVE students per department
    ('day_scholar_percentage',   '65'),   -- must sum to 100 with the next value
    ('hosteller_percentage',     '35'),
    ('random_seed',              '0.424242'),
    -- Trim ACTIVE backlogs above a student's deterministic target so the shape
    -- really is "0 backlogs = majority". This is the only step in the script
    -- that removes rows; it touches synthetic backlog entries only. Set to
    -- 'false' to append-only and never delete.
    ('normalize_backlogs',       'true');

-- Pin the generator so the dataset is reproducible.
SELECT setseed((SELECT value::float8 FROM seed_config WHERE key = 'random_seed'));

DO $$
DECLARE
    d_sum int;
    spd   int;
BEGIN
    SELECT (SELECT value::int FROM pg_temp.seed_config WHERE key = 'students_per_department'),
           (SELECT value::int FROM pg_temp.seed_config WHERE key = 'day_scholar_percentage')
         + (SELECT value::int FROM pg_temp.seed_config WHERE key = 'hosteller_percentage')
      INTO spd, d_sum;
    IF spd < 1 THEN
        RAISE EXCEPTION 'students_per_department must be at least 1';
    END IF;
    IF d_sum <> 100 THEN
        RAISE EXCEPTION 'day_scholar_percentage + hosteller_percentage must equal 100 (got %)', d_sum;
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 1. Name and address vocabulary (synthetic)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS seed_names;
CREATE TEMP TABLE seed_names ON COMMIT DROP AS
SELECT
    ARRAY['Aarav','Vivaan','Aditya','Vihaan','Arjun','Reyansh','Krishna','Ishaan','Rohan','Karan',
           'Ananya','Diya','Aadhya','Saanvi','Ira','Anika','Priya','Neha','Kavya','Meera',
           'Arnav','Advait','Kabir','Vedant','Yash','Rahul','Amit','Suresh','Ravi','Kiran',
           'Sneha','Pooja','Divya','Shreya','Riya','Nandini','Lakshmi','Deepa','Anjali','Sowmya',
           'Harsh','Devansh','Rudra','Atharv','Manav','Nikhil','Siddharth','Parth','Dhruv','Kunal',
           'Nisha','Aishwarya','Bhavana','Charitha','Darshana','Eesha','Gayatri','Harini','Ishita','Jhanvi']::text[] AS first_names,
    ARRAY['Sharma','Verma','Patel','Reddy','Rao','Nair','Iyer','Chowdhury','Banerjee','Mukherjee',
           'Gupta','Mehta','Joshi','Desai','Kulkarni','Bose','Ghosh','Chatterjee','Malhotra','Kapoor',
           'Sinha','Agarwal','Bhat','Menon','Pillai','Krishnan','Ranganathan','Subramanian','Venkatesh','Sundaram',
           'Bhatt','Shah','Trivedi','Pandey','Dubey','Saxena','Agarwal','Thakur','Prasad','Menon']::text[] AS last_names,
    ARRAY['Kumar','Sharma','Reddy','Nair','Patel','Rao','Iyer','Singh']::text[] AS male_middle,
    ARRAY['Krishnan','Bhatt','Menon','Pillai','Sundaram','Nair']::text[] AS female_middle,
    -- Street names only; the "Street" word is added by the address format.
    ARRAY['Nehru','Gandhi','Anna Salai','MG Road','Church','Market',
           'Station','Ramasamy','Bharathiar','Kamarajar']::text[] AS streets,
    -- city and state are kept together so a generated address stays
    -- geographically plausible ("Pune, Tamil Nadu" would not be).
    ARRAY['Coimbatore,Tamil Nadu','Chennai,Tamil Nadu','Bengaluru,Karnataka','Hyderabad,Telangana',
           'Pune,Maharashtra','Madurai,Tamil Nadu','Kochi,Kerala','Vijayawada,Andhra Pradesh']::text[] AS cities,
    ARRAY['FATHER','MOTHER','GUARDIAN']::text[] AS rels;

-- -----------------------------------------------------------------------------
-- 2. Additional subjects so a 3-backlog history is actually representable
-- -----------------------------------------------------------------------------
-- Each department currently has only 2 subjects, which caps a student at 2
-- distinct backlogs. Three more per department are added, purely additively,
-- so the required "3 or more" minority is achievable with real subject
-- references rather than fabricated ones.
INSERT INTO public.subjects (subject_id, subject_code, subject_name, department_id, credits)
SELECT gen_random_uuid(),
       d.department_code || '-' || v.code,
       v.subject_name,
       d.department_id,
       v.credits
FROM public.departments d
CROSS JOIN (VALUES
    ('401', 'Probability and Statistics',        4::numeric),
    ('402', 'Software Engineering',              4::numeric),
    ('403', 'Professional Ethics',               2::numeric)
) AS v(code, subject_name, credits)
WHERE NOT EXISTS (
    SELECT 1 FROM public.subjects s
    WHERE s.department_id = d.department_id AND s.subject_code = d.department_code || '-' || v.code
);

-- -----------------------------------------------------------------------------
-- 3. Plan: how many students each department still needs
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS seed_plan;
CREATE TEMP TABLE seed_plan ON COMMIT DROP AS
WITH cfg AS (
    SELECT (SELECT value::int FROM seed_config WHERE key = 'students_per_department') AS spd
),
-- programs -> batches -> sections. `batches` has no department_id, so the link
-- has to be walked through programs.
link AS (
    SELECT DISTINCT ON (p.department_id)
        p.department_id,
        p.program_id,
        b.batch_id,
        sec.section_id
    FROM public.programs p
    LEFT JOIN public.batches b   ON b.program_id = p.program_id
    LEFT JOIN public.sections sec ON sec.batch_id = b.batch_id
    ORDER BY p.department_id,
             b.batch_id   NULLS LAST,
             sec.section_id NULLS LAST
),
dept AS (
    SELECT
        d.department_id,
        d.department_code,
        (SELECT COUNT(*)::int FROM public.students s
          WHERE s.department_id = d.department_id AND s.status = 'ACTIVE')            AS have,
        COALESCE((SELECT MAX((regexp_match(s.register_number, '^REG-[A-Z]+-([0-9]+)$'))[1]::int)
                    FROM public.students s
                   WHERE s.department_id = d.department_id), 0)                        AS reg_max,
        COALESCE((SELECT MAX((regexp_match(s.admission_number, '^ADM-[A-Z]+-([0-9]+)$'))[1]::int)
                    FROM public.students s
                   WHERE s.department_id = d.department_id), 0)                        AS adm_max
    FROM public.departments d
)
SELECT
    dept.*,
    GREATEST(0, cfg.spd - dept.have) AS to_create,
    link.program_id,
    link.batch_id,
    link.section_id
FROM dept
CROSS JOIN cfg
LEFT JOIN link ON link.department_id = dept.department_id;

-- Fail fast rather than inserting students with dangling foreign keys.
DO $$
DECLARE bad int;
BEGIN
    SELECT COUNT(*) INTO bad FROM seed_plan WHERE to_create > 0 AND (program_id IS NULL OR section_id IS NULL);
    IF bad > 0 THEN
        RAISE EXCEPTION 'Cannot expand: % department(s) have no program/section configured', bad;
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 4. Insert the additional students
-- -----------------------------------------------------------------------------
-- Identifiers continue each department's existing sequence instead of restarting,
-- so REG-/ADM- numbers can never collide with the rows already present.
INSERT INTO public.students
    (register_number, admission_number, first_name, last_name,
     department_id, program_id, batch_id, section_id, status, email, phone)
SELECT
    format('REG-%s-%s', pl.department_code, lpad((pl.reg_max + g.i)::text, 3, '0')),
    format('ADM-%s-%s', pl.department_code, lpad((pl.adm_max + g.i)::text, 3, '0')),
    n.first_names  [1 + floor(random() * array_length(n.first_names,  1))::int],
    n.last_names   [1 + floor(random() * array_length(n.last_names,   1))::int],
    pl.department_id, pl.program_id, pl.batch_id, pl.section_id,
    'ACTIVE',
    -- register suffix guarantees the address is unique even for a repeated name
    lower(n.first_names[1 + floor(random() * array_length(n.first_names, 1))::int]) || '.' ||
    lower(n.last_names [1 + floor(random() * array_length(n.last_names,  1))::int]) ||
    (pl.reg_max + g.i)::text || '@student.institution.edu',
    NULL
FROM seed_plan pl
CROSS JOIN LATERAL generate_series(1, pl.to_create) AS g(i)
CROSS JOIN seed_names n
ON CONFLICT (register_number) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 5. Guardians — one per student, then some families share a guardian
-- -----------------------------------------------------------------------------
-- Every student gets a guardian (including the 180 pre-existing ones, which
-- previously had none). Every 8th student is then re-pointed at the previous
-- student's guardian to model siblings, so a guardian is genuinely shared
-- rather than duplicated per student row.
DROP TABLE IF EXISTS seed_people;
CREATE TEMP TABLE seed_people ON COMMIT DROP AS
SELECT
    s.student_id,
    s.department_id,
    d.department_code,
    row_number() OVER (PARTITION BY s.department_id ORDER BY s.register_number) AS rn,
    gen_random_uuid() AS guardian_id,
    (n.rels[1 + floor(random() * array_length(n.rels, 1))::int]) AS relationship
FROM public.students s
JOIN public.departments d ON d.department_id = s.department_id
CROSS JOIN seed_names n
WHERE NOT EXISTS (SELECT 1 FROM public.guardians g WHERE g.guardian_id = s.parent_id);

INSERT INTO public.guardians
    (guardian_id, parent_name, parent_phone, parent_address, relationship, email)
SELECT
    sp.guardian_id,
    btrim(
        n.first_names[1 + floor(random() * array_length(n.first_names, 1))::int] || ' ' ||
        n.last_names [1 + floor(random() * array_length(n.last_names,  1))::int]
    ),
    -- Clearly synthetic test-data block, stored as text so +91 is preserved.
    '+9190000' || lpad(sp.rn::text, 5, '0'),
    format('%s, %s Street, %s %s',
           (1 + floor(random() * 120))::int,
           n.streets[1 + floor(random() * array_length(n.streets, 1))::int],
           n.cities [1 + floor(random() * array_length(n.cities,  1))::int],
           lpad((600000 + floor(random() * 99999))::int::text, 6, '0')),
    sp.relationship,
    NULL
FROM seed_people sp CROSS JOIN seed_names n
ON CONFLICT (guardian_id) DO NOTHING;

UPDATE public.students s
   SET parent_id = sp.guardian_id
  FROM seed_people sp
 WHERE s.student_id = sp.student_id;

-- Siblings: every 8th student shares the previous student's guardian.
WITH ordered AS (
    SELECT student_id, guardian_id,
           lag(guardian_id) OVER (PARTITION BY department_id ORDER BY rn) AS prev_guardian,
           rn
    FROM seed_people
)
UPDATE public.students s
   SET parent_id = o.prev_guardian
  FROM ordered o
 WHERE s.student_id = o.student_id
   AND o.prev_guardian IS NOT NULL
   AND o.rn % 8 = 0
   AND o.prev_guardian <> o.guardian_id;

-- Guardians that ended up unreferenced (an overwritten duplicate) are removed so
-- the table holds no orphan contacts.
DELETE FROM public.guardians g
 WHERE NOT EXISTS (SELECT 1 FROM public.students s WHERE s.parent_id = g.guardian_id);

-- -----------------------------------------------------------------------------
-- 6. Residency — DAY_SCHOLAR / HOSTELLER
-- -----------------------------------------------------------------------------
-- Existing rows are refreshed rather than skipped, so re-running always leaves
-- a correct DAY_SCHOLAR/HOSTELLER split.
--
-- The type and the room are decided in the same statement: an earlier version
-- inserted HOSTELLER with a NULL hostel and back-filled it afterwards, which
-- the `student_residency_hosteller_placed_check` constraint correctly rejected.
--
-- GOTCHA worth recording: an *uncorrelated* LATERAL subquery in FROM is
-- evaluated ONCE by PostgreSQL, and its single result is then joined to every
-- row. The first version of this block chose the type inside such a LATERAL and
-- so classified all 300 students DAY_SCHOLAR. MATERIALIZED, plus an explicit
-- correlation to the student, is what makes it per-row.
WITH room_index AS MATERIALIZED (
    SELECT hostel_id, room_id,
           row_number() OVER (ORDER BY hostel_id, room_number) AS idx,
           COUNT(*)     OVER ()                                  AS total
    FROM public.rooms
),
residency_pick AS MATERIALIZED (
    SELECT
        s.student_id,
        CASE
            WHEN random() < (SELECT value::float8 / 100 FROM seed_config WHERE key = 'day_scholar_percentage')
                THEN 'DAY_SCHOLAR'
            ELSE 'HOSTELLER'
        END AS residency_type,
        ri.hostel_id,
        ri.room_id
    FROM public.students s
    LEFT JOIN LATERAL (
        -- Correlated to s.register_number, so it is evaluated per student.
        -- Hash-based rather than random: this spreads placements evenly and
        -- keeps a given register number's placement stable.
        SELECT hostel_id, room_id
        FROM room_index
        WHERE idx = 1 + mod(abs(hashtext(s.register_number)), total)
    ) ri ON TRUE
)
INSERT INTO public.student_residency (student_id, residency_type, hostel_id, room_id)
SELECT
    rp.student_id,
    rp.residency_type,
    CASE WHEN rp.residency_type = 'HOSTELLER' THEN rp.hostel_id END,
    CASE WHEN rp.residency_type = 'HOSTELLER' THEN rp.room_id   END
FROM residency_pick rp
-- Never emit a hosteller with nowhere to live, even if the room table is empty.
WHERE rp.residency_type = 'DAY_SCHOLAR' OR rp.hostel_id IS NOT NULL
ON CONFLICT (student_id) DO UPDATE
    SET residency_type = EXCLUDED.residency_type,
        hostel_id      = EXCLUDED.hostel_id,
        room_id        = EXCLUDED.room_id,
        updated_at     = NOW();

-- -----------------------------------------------------------------------------
-- 7. CGPA — via the existing student_academic_summary
-- -----------------------------------------------------------------------------
-- No cgpa column is added to `students`. The summary row is the single source,
-- upserted here for every student. Values spread across 5.50-9.89 with more mass
-- in the 7.5-9.5 band, which is what a real cohort looks like; previously all
-- six departments averaged an identical 8.07.
--
-- MATERIALIZED matters here. Without it the per-student random() is evaluated
-- once and every student gets the same CGPA, which is exactly the artificial
-- pattern this expansion is meant to remove.
WITH cg AS MATERIALIZED (
    SELECT
        s.student_id,
        ROUND((
            CASE
                WHEN random() < 0.08 THEN 5.50 + random() * 0.90
                WHEN random() < 0.24 THEN 6.40 + random() * 1.10
                WHEN random() < 0.54 THEN 7.50 + random() * 1.00
                WHEN random() < 0.84 THEN 8.50 + random() * 1.00
                ELSE 9.50 + random() * 0.39
            END
        )::numeric, 2) AS cgpa
    FROM public.students s
)
INSERT INTO public.student_academic_summary
    (summary_id, student_id, current_cgpa, current_sgpa, backlog_count, updated_at)
SELECT
    gen_random_uuid(),
    cg.student_id,
    cg.cgpa,
    LEAST(10::numeric, ROUND((cg.cgpa + (random() * 0.45 - 0.10))::numeric, 2)),
    0,
    NOW()
FROM cg
ON CONFLICT (student_id) DO UPDATE
    SET current_cgpa = EXCLUDED.current_cgpa,
        current_sgpa = EXCLUDED.current_sgpa,
        updated_at  = NOW();

-- -----------------------------------------------------------------------------
-- 8. Backlogs — the `backlogs` table is the source of truth
-- -----------------------------------------------------------------------------
-- Targets are per student, not per department. Existing backlog rows are kept;
-- only the shortfall is topped up, using subjects from the student's own
-- department that they do not already have a backlog in.
--
-- The target is DERIVED FROM A HASH OF THE STUDENT ID, not from random(). That
-- matters for idempotency: with random() targets, a second run re-rolls every
-- student and top-ups on top of the first run, so the distribution compounds
-- away from the configured shape on each execution. Hashing makes the target
-- stable, so re-running converges instead of drifting.
WITH targets AS (
    SELECT
        s.student_id,
        s.department_id,
        CASE
            WHEN mod(abs(hashtext(s.student_id::text)), 100) < 60 THEN 0
            WHEN mod(abs(hashtext(s.student_id::text)), 100) < 82 THEN 1
            WHEN mod(abs(hashtext(s.student_id::text)), 100) < 94 THEN 2
            ELSE 3
        END AS target
    FROM public.students s
),
deficit AS (
    SELECT
        t.student_id,
        t.department_id,
        GREATEST(0, t.target - (
            SELECT COUNT(*)::int FROM public.backlogs b
             WHERE b.student_id = t.student_id AND b.status = 'ACTIVE'
        )) AS need
    FROM targets t
)
INSERT INTO public.backlogs (student_id, subject_id, semester_id, status)
SELECT
    df.student_id,
    sub.subject_id,
    sem.semester_id,
    'ACTIVE'
FROM deficit df
CROSS JOIN LATERAL generate_series(1, df.need) AS g(i)
CROSS JOIN LATERAL (
    SELECT s.subject_id
    FROM public.subjects s
    WHERE s.department_id = df.department_id
      AND NOT EXISTS (
          SELECT 1 FROM public.backlogs b2
           WHERE b2.student_id = df.student_id AND b2.subject_id = s.subject_id
      )
    ORDER BY s.subject_code
    LIMIT 1 OFFSET (g.i - 1)
) sub
CROSS JOIN LATERAL (
    SELECT semester_id FROM public.semesters WHERE is_current LIMIT 1
) sem;

-- Trim to the deterministic target. Append-only seeding cannot reach the
-- required shape, because a student who already holds more backlogs than their
-- target would keep them and "0 backlogs" would never become the majority.
-- Ranked per student so exactly the surplus is removed and the survivors are
-- stable across runs.
DELETE FROM public.backlogs b
 WHERE b.status = 'ACTIVE'
   AND (SELECT value FROM seed_config WHERE key = 'normalize_backlogs') = 'true'
   AND b.backlog_id IN (
       SELECT ranked.backlog_id
       FROM (
           SELECT b2.backlog_id,
                  b2.student_id,
                  row_number() OVER (PARTITION BY b2.student_id ORDER BY b2.backlog_id) AS rn
           FROM public.backlogs b2
           WHERE b2.status = 'ACTIVE'
       ) ranked
       JOIN (
           SELECT s.student_id,
                  CASE
                      WHEN mod(abs(hashtext(s.student_id::text)), 100) < 60 THEN 0
                      WHEN mod(abs(hashtext(s.student_id::text)), 100) < 82 THEN 1
                      WHEN mod(abs(hashtext(s.student_id::text)), 100) < 94 THEN 2
                      ELSE 3
                  END AS target
           FROM public.students s
       ) t ON t.student_id = ranked.student_id
       WHERE ranked.rn > t.target
   );

-- Keep the cached count aligned with reality.
UPDATE public.student_academic_summary sa
   SET backlog_count = COALESCE((
       SELECT COUNT(*)::int FROM public.backlogs b
        WHERE b.student_id = sa.student_id AND b.status = 'ACTIVE'
   ), 0);

-- -----------------------------------------------------------------------------
-- 9. Attendance — regenerated, randomized per record
-- -----------------------------------------------------------------------------
-- The existing mark sheets are replaced. They were the source of the department
-- bias this expansion is meant to remove: five of six departments sat at exactly
-- 97.67% while AIML sat at 87.00%, which is an artefact of how they were
-- generated rather than anything about those departments.
--
-- The replacement assigns each STUDENT an attendance propensity and then draws
-- each record independently, so department averages emerge from the data instead
-- of being imposed. OD counts as attended, matching the existing
-- student_attendance_percentage view and its own documented business rule.
CREATE TEMP TABLE seed_attendance_dates ON COMMIT DROP AS
SELECT DISTINCT attendance_date FROM public.attendance;

DELETE FROM public.attendance;

-- Fallback if the table had been empty, so this script also seeds a fresh DB.
INSERT INTO seed_attendance_dates (attendance_date)
SELECT gs::date
FROM generate_series(DATE '2023-09-04', DATE '2023-10-16', INTERVAL '7 days') gs
WHERE NOT EXISTS (SELECT 1 FROM seed_attendance_dates);

WITH props AS MATERIALIZED (
    SELECT
        s.student_id,
        CASE
            WHEN random() < 0.10 THEN 0.960 + random() * 0.030
            WHEN random() < 0.35 THEN 0.850 + random() * 0.100
            WHEN random() < 0.62 THEN 0.750 + random() * 0.100
            WHEN random() < 0.85 THEN 0.600 + random() * 0.150
            ELSE                        random() * 0.200
        END AS propensity
    FROM public.students s
)
INSERT INTO public.attendance (attendance_id, student_id, offering_id, attendance_date, status, marked_by)
SELECT
    gen_random_uuid(),
    pr.student_id,
    co.offering_id,
    dt.attendance_date,
    CASE
        WHEN random() < 0.030 THEN 'OD'
        WHEN random() < pr.propensity THEN 'PRESENT'
        ELSE 'ABSENT'
    END,
    co.faculty_id
FROM props pr
JOIN public.students   s   ON s.student_id  = pr.student_id
JOIN public.subjects   sub ON sub.department_id = s.department_id
JOIN public.course_offerings co ON co.subject_id = sub.subject_id
CROSS JOIN seed_attendance_dates dt;

COMMIT;

-- =============================================================================
-- Verification (runs after COMMIT; read-only)
-- =============================================================================
\echo '--- 1. total students ---'
SELECT COUNT(*) AS total_students FROM public.students;

\echo '--- 2. ACTIVE students per department (expect the configured target) ---'
SELECT d.department_name,
       COUNT(*) FILTER (WHERE s.status = 'ACTIVE') AS active_students
FROM public.departments d
LEFT JOIN public.students s ON s.department_id = d.department_id
GROUP BY d.department_name
ORDER BY d.department_name;

\echo '--- 3. duplicate register numbers (expect 0 rows) ---'
SELECT register_number, COUNT(*) FROM public.students
GROUP BY register_number HAVING COUNT(*) > 1;

\echo '--- 4. duplicate admission numbers (expect 0 rows) ---'
SELECT admission_number, COUNT(*) FROM public.students
WHERE admission_number IS NOT NULL
GROUP BY admission_number HAVING COUNT(*) > 1;

\echo '--- 5. residency split (expect both categories) ---'
SELECT residency_type, COUNT(*) FROM public.student_residency GROUP BY residency_type ORDER BY 1;

\echo '--- 6. backlogs: cached count vs derived count (expect 0 mismatches) ---'
SELECT COUNT(*) AS mismatches
FROM public.student_academic_summary sa
WHERE sa.backlog_count <> (
    SELECT COUNT(*)::int FROM public.backlogs b
     WHERE b.student_id = sa.student_id AND b.status = 'ACTIVE'
);

\echo '--- 7. CGPA range (expect 5.50 - 9.89) ---'
SELECT MIN(current_cgpa) AS min_cgpa, MAX(current_cgpa) AS max_cgpa,
       ROUND(AVG(current_cgpa), 3) AS avg_cgpa, COUNT(DISTINCT current_cgpa) AS distinct_values
FROM public.student_academic_summary;

\echo '--- 8. every student has a valid guardian ---'
SELECT COUNT(*) AS students_without_guardian
FROM public.students s WHERE s.parent_id IS NULL;

\echo '--- 9. attendance derived from records, spread by student ---'
SELECT
    CASE
        WHEN attendance_percentage >= 95 THEN '95%+'
        WHEN attendance_percentage >= 85 THEN '85-95%'
        WHEN attendance_percentage >= 75 THEN '75-85%'
        WHEN attendance_percentage >= 60 THEN '60-75%'
        ELSE 'below 60%'
    END AS band,
    COUNT(*) AS students
FROM public.student_attendance_percentage
GROUP BY 1 ORDER BY 1;

\echo '--- 10. department attendance (must NOT be uniform by design) ---'
SELECT d.department_code,
       COUNT(*) AS records,
       ROUND(100.0 * COUNT(*) FILTER (WHERE a.status IN ('PRESENT','OD')) / COUNT(*), 2) AS pct_attended
FROM public.attendance a
JOIN public.students s   ON s.student_id = a.student_id
JOIN public.departments d ON d.department_id = s.department_id
GROUP BY d.department_code ORDER BY d.department_code;

\echo '--- 11. students per department attendance spread (SD across departments, expect non-zero) ---'
SELECT ROUND(STDDEV(pct)::numeric, 4) AS stddev_across_departments
FROM (
    SELECT 100.0 * COUNT(*) FILTER (WHERE a.status IN ('PRESENT','OD')) / COUNT(*) AS pct
    FROM public.attendance a
    JOIN public.students s ON s.student_id = a.student_id
    GROUP BY s.department_id
) t;
